name: gita # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.7.8+git' # just for humans, typically '1.2+git' or '1.3.2'
summary: Manage multiple git repos side by side for sanity # 79 char long summary
description: |
  This tool does two things display the status of multiple git repos such as branch, modification,
  commit message side by side and delegate git commands/aliases from any working directory. If 
  several repos need to be compiled against each other, it helps to see their status together. 
  I also hate to change directories to execute git commands.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  gita:
    # See 'snapcraft plugins'
    plugin: python
    source: .
    stage-packages:
      - python-six

apps:
  gita:
    command: python3 -m gita
    plugs:
      - home
